name: Deploy ExpenseTrack Backend AWS EC2

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_HOST: 15.206.90.12
      AWS_USER: ubuntu

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Add Host Key
        run: |
          ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts

      - name: Deploy and Restart Backend
        run: |
          ssh $AWS_USER@$AWS_HOST << 'EOF'
          cd /home/ubuntu/ExpenseTrack-Backend-
          git pull origin main
          npm ci
          pm2 reload expenseTrackbe --update-env
          EOF